[build]
  publish = "."

[[redirects]]
  from = "/tr/p/:brand/:product"
  to = "/product-detail.html"
  status = 200

[[redirects]]
  from = "/p/:brand/:product"
  to = "/product-detail.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
