[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 4321
  port = 8888

[[redirects]]
  from = "/tr/p/:brand/:product"
  to = "/product-detail.html"
  status = 200

[[redirects]]
  from = "/p/:brand/:product"
  to = "/product-detail.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
